services:
  - type: web
    name: anonim-messaging-bot
    runtime: docker
    repo: https://github.com/anames2323/Amordonskiy
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
